apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-main
data:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m

    route:
      receiver: 'slack'
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h

    receivers:
      - name: 'slack'
        slack_configs:
          - send_resolved: true
            #username: ''
            channel: '#<CHANNEL>'
            api_url: 'https://hooks.slack.com/services/<YOUR TOKEN HERE>'
